package com.forum.model.entity;

import java.util.Date;

public class Comment {
	
	
	
    public Comment() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Comment(Integer cid, Date commenttime, Integer uid, Integer pid, String text) {
		super();
		this.cid = cid;
		this.commenttime = commenttime;
		this.uid = uid;
		this.pid = pid;
		this.text = text;
	}

	@Override
	public String toString() {
		return "Comment [cid=" + cid + ", commenttime=" + commenttime + ", uid=" + uid + ", pid=" + pid + ", text="
				+ text + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.cid
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commenttime
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    private Date commenttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.uid
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.pid
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.text
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.cid
     *
     * @return the value of comment.cid
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.cid
     *
     * @param cid the value for comment.cid
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commenttime
     *
     * @return the value of comment.commenttime
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    public Date getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commenttime
     *
     * @param commenttime the value for comment.commenttime
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    public void setCommenttime(Date commenttime) {
        this.commenttime = commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.uid
     *
     * @return the value of comment.uid
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.uid
     *
     * @param uid the value for comment.uid
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.pid
     *
     * @return the value of comment.pid
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.pid
     *
     * @param pid the value for comment.pid
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.text
     *
     * @return the value of comment.text
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.text
     *
     * @param text the value for comment.text
     *
     * @mbg.generated Wed Oct 21 17:27:33 GMT+08:00 2020
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}