package com.forum.model.entity;

import java.util.Date;

public class Loginrecord {
	
	
    public Loginrecord() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Loginrecord(Integer rid, Date logtime, Integer uid) {
		super();
		this.rid = rid;
		this.logtime = logtime;
		this.uid = uid;
	}

	@Override
	public String toString() {
		return "Loginrecord [rid=" + rid + ", logtime=" + logtime + ", uid=" + uid + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginrecord.rid
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginrecord.logtime
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    private Date logtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginrecord.uid
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginrecord.rid
     *
     * @return the value of loginrecord.rid
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginrecord.rid
     *
     * @param rid the value for loginrecord.rid
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginrecord.logtime
     *
     * @return the value of loginrecord.logtime
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    public Date getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginrecord.logtime
     *
     * @param logtime the value for loginrecord.logtime
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginrecord.uid
     *
     * @return the value of loginrecord.uid
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginrecord.uid
     *
     * @param uid the value for loginrecord.uid
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}