package com.forum.model.entity;

import java.util.Date;

public class Post {
	
	
	
    public Post() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Post(Integer pid, String title, Integer uid, Integer kind, Date begintime, String text) {
		super();
		this.pid = pid;
		this.title = title;
		this.uid = uid;
		this.kind = kind;
		this.begintime = begintime;
		this.text = text;
	}

	@Override
	public String toString() {
		return "Post [pid=" + pid + ", title=" + title + ", uid=" + uid + ", kind=" + kind + ", begintime=" + begintime
				+ ", text=" + text + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.pid
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.uid
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.kind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    private Integer kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.begintime
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    private Date begintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.text
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.pid
     *
     * @return the value of post.pid
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.pid
     *
     * @param pid the value for post.pid
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.uid
     *
     * @return the value of post.uid
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.uid
     *
     * @param uid the value for post.uid
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.kind
     *
     * @return the value of post.kind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public Integer getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.kind
     *
     * @param kind the value for post.kind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public void setKind(Integer kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.begintime
     *
     * @return the value of post.begintime
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.begintime
     *
     * @param begintime the value for post.begintime
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.text
     *
     * @return the value of post.text
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.text
     *
     * @param text the value for post.text
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}