package com.forum.model.entity;

public class Postkind {
	
	
    public Postkind() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Postkind(Integer kid, String kind) {
		super();
		this.kid = kid;
		this.kind = kind;
	}

	@Override
	public String toString() {
		return "Postkind [kid=" + kid + ", kind=" + kind + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postkind.kid
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    private Integer kid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postkind.kind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    private String kind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postkind.kid
     *
     * @return the value of postkind.kid
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public Integer getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postkind.kid
     *
     * @param kid the value for postkind.kid
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public void setKid(Integer kid) {
        this.kid = kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postkind.kind
     *
     * @return the value of postkind.kind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column postkind.kind
     *
     * @param kind the value for postkind.kind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }
}