package com.forum.model.entity;

public class Userinfo {
	
	
    public Userinfo() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Userinfo(Integer uid, String username, String userpwd, String email, String sex, Integer portrait) {
		super();
		this.uid = uid;
		this.username = username;
		this.userpwd = userpwd;
		this.email = email;
		this.sex = sex;
		this.portrait = portrait;
	}

	@Override
	public String toString() {
		return "Userinfo [uid=" + uid + ", username=" + username + ", userpwd=" + userpwd + ", email=" + email
				+ ", sex=" + sex + ", portrait=" + portrait + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uid
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userpwd
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    private String userpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.email
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.sex
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.portrait
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    private Integer portrait;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uid
     *
     * @return the value of userinfo.uid
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uid
     *
     * @param uid the value for userinfo.uid
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userpwd
     *
     * @return the value of userinfo.userpwd
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userpwd
     *
     * @param userpwd the value for userinfo.userpwd
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.email
     *
     * @return the value of userinfo.email
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.email
     *
     * @param email the value for userinfo.email
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.sex
     *
     * @return the value of userinfo.sex
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.sex
     *
     * @param sex the value for userinfo.sex
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.portrait
     *
     * @return the value of userinfo.portrait
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public Integer getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.portrait
     *
     * @param portrait the value for userinfo.portrait
     *
     * @mbg.generated Wed Sep 23 15:46:13 GMT+08:00 2020
     */
    public void setPortrait(Integer portrait) {
        this.portrait = portrait;
    }
}