package com.forum.model.dao;

import com.forum.model.entity.Loginrecord;
import com.forum.model.entity.LoginrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginrecord
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    long countByExample(LoginrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginrecord
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    int deleteByExample(LoginrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginrecord
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginrecord
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    int insert(Loginrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginrecord
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    int insertSelective(Loginrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginrecord
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    List<Loginrecord> selectByExample(LoginrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginrecord
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    Loginrecord selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginrecord
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Loginrecord record, @Param("example") LoginrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginrecord
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Loginrecord record, @Param("example") LoginrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginrecord
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Loginrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginrecord
     *
     * @mbg.generated Fri Sep 25 21:31:03 GMT+08:00 2020
     */
    int updateByPrimaryKey(Loginrecord record);
}