package com.forum.model.dao;

import com.forum.model.entity.Postkind;
import com.forum.model.entity.PostkindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostkindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postkind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    long countByExample(PostkindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postkind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    int deleteByExample(PostkindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postkind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer kid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postkind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    int insert(Postkind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postkind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    int insertSelective(Postkind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postkind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    List<Postkind> selectByExample(PostkindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postkind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    Postkind selectByPrimaryKey(Integer kid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postkind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Postkind record, @Param("example") PostkindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postkind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Postkind record, @Param("example") PostkindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postkind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Postkind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postkind
     *
     * @mbg.generated Tue Sep 29 20:32:32 GMT+08:00 2020
     */
    int updateByPrimaryKey(Postkind record);
}